// SERIAL TEMPERATURA
// INFACI-SENAI SÃO CARLOS
// CSTADS
//02/04/2025
//AUTOR: TONY EMERSON MARIM

int SNESOR = 0;   // DEFINE O PINE ANALOGICO AO COMO ENTRADA DO SENSOR
float D = 0;   // VARIAVEL PAR ARMAZENAR O VALOR LIDO DO SENSOR (0-1023)
int T = 0;   // VARIAVEL PARA ARMAZENAR A TEMPERATURA CALCULADA

void setup(){
  Serial.Begin(9600);   // INICIA A COMUNICACAO SERIAL COM TAXA DE 9600 BAUDS
}

void loop(){
  D = analogRead(SENSOR);
  T = (D * 5 * 100)/1023; //  COVERTE O VALOR LIDO PAR TEMPERATURA
  Serial.print(T);  //  ENVIA O VALOR DA TEMPERATURA PARA O SERIAL
  delay(1000);  // AGUARDA 1 SEGUNDO PARA A PROXIMA LEITURA
}


int main(void){
  init ();  // INICIALIZA O HARDWARE (FUNCAO INTERNA DO ARDUINO)
  steup();  //  CHAMA A FUCAO SETUP
  for (;;)  // LOOP INFINITO
    loop(); // CHAMA CONTINUAMENTE A FUNCAO LOOP

  return 0;   
}