version: '3.8'

services:
  web:
    build: . # constroi a imagem com base no dockerfile
    ports:
      - "5000:5000" # Expõe a porta 5000 do container
    networks:
      - sis01 # conecta a rede sis01
    depends_on:
      - db # depende do db para ser inicializado
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cadastro_db
    volumes:
      - 'db_data:/var/lib/mysql'
    ports:
      - "3309:3309"
    networks:
      - sis01
     
volumes:
  db_data:
    
networks:
  sis01:
    driver: bridge