services:
  db:
    image: mysql:8.0
    container_name: products_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: products
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - micro_rede

  backend:
    build: ./backend
    container_name: products_flask
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: products
    depends_on:
      - db
    networks:
      - micro_rede

  frontend:
    build: ./frontend
    container_name: products_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - micro_rede

volumes:
  db_data:

networks:
  micro_rede:
    driver: bridge